stages:
  - sast
  - dast

bearer-sast:
  stage: sast
  image:
    name: bearer/bearer
    entrypoint: [""]
  script: bearer scan . --format gitlab-sast --output gl-sast-report.json || true
  artifacts:
    paths:
      - gl-sast-report.json

semgrep-sast:
  stage: sast
  image: semgrep/semgrep
  script:
    - semgrep --config auto --json --output semgrep-report.json $CI_PROJECT_DIR || true
  artifacts:
    paths:
      - semgrep-report.json

dast:
  stage: dast
  image: docker:latest
  services: 
    - docker:dind
  script:
    - unset DOCKER_HOST
    - docker-compose up -d
    - docker run --name nikto --rm --network test_my_app_network -u $(id -u ${USER}):$(id -g ${USER}) hysnsec/nikto -host http://app:8080 || true
    - docker-compose down

zap_scan:
  stage: dast
  image: docker:latest
  services: 
    - docker:dind
  script:
    - unset DOCKER_HOST
    - docker-compose up -d
    - docker run --name zap-container --rm --network test_my_app_network -u $(id -u ${USER}):$(id -g ${USER}) ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://app:8080 || true
    - docker-compose down
